### ISSUE TITLE
IOError: Unable to open file (File signature not found)

### ISSUE THREAD

**Issue by aadarshpratik1** [asingh33/CNNGestureRecognizer#13]
Hi..... I am gett

Traceback (most recent call last):
  File "trackgesture.py", line 299, in <module>
    Main()
  File "trackgesture.py", line 175, in Main
    mod = myNN.loadCNN(0)
  File "/Users/aadarshpratik/anaconda2/CNNGestureRecognizer/gestureCNN.py", line 174, in loadCNN
    model.load_weights(fname)
  File "/Users/aadarshpratik/anaconda2/lib/python2.7/site-packages/keras/models.py", line 708, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/Users/aadarshpratik/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/Users/aadarshpratik/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (File signature not found)
ᐧ

**Comment by aadarshpratik1** [comment]
*I Am getting this error whenever I try running it...... Can u explain how to sort it out?? 
Thank you

**Comment by aadarshpratik1** [comment]
I am using a MacBook btw
