### ISSUE TITLE
I run it encounter resource exhausted: OOM

### ISSUE THREAD

**Issue by jyhflash** [asingh33/CNNGestureRecognizer#37]
when i train my own model,problems happened.I run it encounter resource exhausted: OOM.
could you help me?

**Comment by jyhflash** [comment]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_1 (Conv2D)            (None, 32, 198, 198)      320       
_________________________________________________________________
activation_1 (Activation)    (None, 32, 198, 198)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 196, 196)      9248      
_________________________________________________________________
activation_2 (Activation)    (None, 32, 196, 196)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 32, 98, 98)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 32, 98, 98)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 307328)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               39338112  
_________________________________________________________________
activation_3 (Activation)    (None, 128)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 645       
_________________________________________________________________
activation_4 (Activation)    (None, 5)                 0         
=================================================================
Total params: 39,348,325
Trainable params: 39,348,325
Non-trainable params: 0
_________________________________________________________________
(903, 40000)
Press any key
samples_per_class -  180.6
Train on 577 samples, validate on 145 samples
Epoch 1/15
2019-02-13 11:51:24.120936: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 229.7KiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-02-13 11:51:24.121381: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 43.07MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-02-13 11:51:24.121763: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 517.50MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-02-13 11:51:24.122119: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.0KiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-02-13 11:51:24.122528: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 8.95MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-02-13 11:51:24.122870: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 362.55MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-02-13 11:51:34.125484: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 36.0KiB.  Current allocation summary follows.
2019-02-13 11:51:34.125745: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (256): 	Total Chunks: 54, Chunks in use: 54. 13.5KiB allocated for chunks. 13.5KiB in use in bin. 2.4KiB client-requested in use in bin.
2019-02-13 11:51:34.126030: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (512): 	Total Chunks: 8, Chunks in use: 8. 4.3KiB allocated for chunks. 4.3KiB in use in bin. 4.1KiB client-requested in use in bin.
2019-02-13 11:51:34.126288: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (1024): 	Total Chunks: 8, Chunks in use: 8. 10.0KiB allocated for chunks. 10.0KiB in use in bin. 8.9KiB client-requested in use in bin.
2019-02-13 11:51:34.127219: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (2048): 	Total Chunks: 7, Chunks in use: 7. 17.5KiB allocated for chunks. 17.5KiB in use in bin. 17.5KiB client-requested in use in bin.
2019-02-13 11:51:34.127699: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.128251: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.128905: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (16384): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.129145: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (32768): 	Total Chunks: 7, Chunks in use: 7. 252.0KiB allocated for chunks. 252.0KiB in use in bin. 252.0KiB client-requested in use in bin.
2019-02-13 11:51:34.129461: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (65536): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.130266: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (131072): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.131565: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (262144): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.131914: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (524288): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.132299: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.132716: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.133016: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (4194304): 	Total Chunks: 1, Chunks in use: 1. 4.88MiB allocated for chunks. 4.88MiB in use in bin. 4.88MiB client-requested in use in bin.
2019-02-13 11:51:34.133305: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.133632: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.133886: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.134146: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.134476: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (134217728): 	Total Chunks: 9, Chunks in use: 9. 1.36GiB allocated for chunks. 1.36GiB in use in bin. 1.32GiB client-requested in use in bin.
2019-02-13 11:51:34.134755: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:630] Bin (268435456): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-02-13 11:51:34.135005: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:646] Bin for 36.0KiB was 32.0KiB, Chunk State: 
2019-02-13 11:51:34.135189: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C0000 of size 1280
2019-02-13 11:51:34.135336: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C0500 of size 256
2019-02-13 11:51:34.135522: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C0600 of size 256
2019-02-13 11:51:34.135668: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C0700 of size 256
2019-02-13 11:51:34.135815: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C0800 of size 256
2019-02-13 11:51:34.135976: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C0900 of size 1280
2019-02-13 11:51:34.138054: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C0E00 of size 256
2019-02-13 11:51:34.138189: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C0F00 of size 256
2019-02-13 11:51:34.138322: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C1000 of size 256
2019-02-13 11:51:34.138742: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C1100 of size 256
2019-02-13 11:51:34.138861: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C1200 of size 256
2019-02-13 11:51:34.138976: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C1300 of size 256
2019-02-13 11:51:34.139097: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C1400 of size 256
2019-02-13 11:51:34.139254: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C1500 of size 256
2019-02-13 11:51:34.139422: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C1600 of size 256
2019-02-13 11:51:34.139591: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019C1700 of size 36864
2019-02-13 11:51:34.139740: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005019CA700 of size 157351936
2019-02-13 11:51:34.139893: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDA700 of size 512
2019-02-13 11:51:34.140041: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDA900 of size 2560
2019-02-13 11:51:34.140214: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDB300 of size 256
2019-02-13 11:51:34.140365: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDB400 of size 1280
2019-02-13 11:51:34.141268: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDB900 of size 256
2019-02-13 11:51:34.141664: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDBA00 of size 256
2019-02-13 11:51:34.142144: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDBB00 of size 256
2019-02-13 11:51:34.142322: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDBC00 of size 256
2019-02-13 11:51:34.142503: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFDBD00 of size 36864
2019-02-13 11:51:34.142683: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000050AFE4D00 of size 157351936
2019-02-13 11:51:34.142842: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005145F4D00 of size 2560
2019-02-13 11:51:34.143002: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005145F5700 of size 36864
2019-02-13 11:51:34.143164: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 00000005145FE700 of size 36864
2019-02-13 11:51:34.143326: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000514607700 of size 157351936
2019-02-13 11:51:34.143540: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000051DC17700 of size 157351936
2019-02-13 11:51:34.143700: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527227700 of size 512
2019-02-13 11:51:34.143859: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527227900 of size 512
2019-02-13 11:51:34.144020: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527227B00 of size 512
2019-02-13 11:51:34.144198: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527227D00 of size 2560
2019-02-13 11:51:34.145482: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527228700 of size 2560
2019-02-13 11:51:34.145767: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527229100 of size 256
2019-02-13 11:51:34.145918: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527229200 of size 256
2019-02-13 11:51:34.146057: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527229300 of size 256
2019-02-13 11:51:34.146690: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527229400 of size 1280
2019-02-13 11:51:34.146923: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527229900 of size 1280
2019-02-13 11:51:34.147200: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527229E00 of size 256
2019-02-13 11:51:34.148136: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000527229F00 of size 256
2019-02-13 11:51:34.148334: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A000 of size 256
2019-02-13 11:51:34.148606: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A100 of size 256
2019-02-13 11:51:34.148754: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A200 of size 256
2019-02-13 11:51:34.148912: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A300 of size 256
2019-02-13 11:51:34.149065: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A400 of size 256
2019-02-13 11:51:34.149256: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A500 of size 256
2019-02-13 11:51:34.150007: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A600 of size 256
2019-02-13 11:51:34.150184: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A700 of size 256
2019-02-13 11:51:34.150312: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A800 of size 256
2019-02-13 11:51:34.150519: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722A900 of size 256
2019-02-13 11:51:34.150672: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722AA00 of size 256
2019-02-13 11:51:34.150858: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722AB00 of size 256
2019-02-13 11:51:34.151029: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722AC00 of size 256
2019-02-13 11:51:34.151234: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722AD00 of size 256
2019-02-13 11:51:34.152097: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722AE00 of size 256
2019-02-13 11:51:34.152307: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722AF00 of size 256
2019-02-13 11:51:34.152456: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722B000 of size 256
2019-02-13 11:51:34.152632: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722B100 of size 256
2019-02-13 11:51:34.152784: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722B200 of size 256
2019-02-13 11:51:34.152940: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722B300 of size 768
2019-02-13 11:51:34.153120: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052722B600 of size 5120000
2019-02-13 11:51:34.153280: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052770D600 of size 256
2019-02-13 11:51:34.154047: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052770D700 of size 256
2019-02-13 11:51:34.154250: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000052770D800 of size 157351936
2019-02-13 11:51:34.154446: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000530D1D800 of size 157351936
2019-02-13 11:51:34.154600: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000053A32D800 of size 157351936
2019-02-13 11:51:34.154777: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054393D800 of size 512
2019-02-13 11:51:34.154910: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054393DA00 of size 512
2019-02-13 11:51:34.155061: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054393DC00 of size 512
2019-02-13 11:51:34.155260: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054393DE00 of size 1280
2019-02-13 11:51:34.156003: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054393E300 of size 1280
2019-02-13 11:51:34.156188: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054393E800 of size 1280
2019-02-13 11:51:34.156393: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054393ED00 of size 2560
2019-02-13 11:51:34.156583: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054393F700 of size 2560
2019-02-13 11:51:34.156841: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543940100 of size 2560
2019-02-13 11:51:34.157056: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543940B00 of size 256
2019-02-13 11:51:34.157309: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543940C00 of size 256
2019-02-13 11:51:34.157529: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543940D00 of size 256
2019-02-13 11:51:34.158486: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543940E00 of size 256
2019-02-13 11:51:34.158625: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543940F00 of size 256
2019-02-13 11:51:34.158760: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543941000 of size 256
2019-02-13 11:51:34.158894: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543941100 of size 256
2019-02-13 11:51:34.159031: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543941200 of size 36864
2019-02-13 11:51:34.159227: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054394A200 of size 36864
2019-02-13 11:51:34.159428: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 0000000543953200 of size 36864
2019-02-13 11:51:34.159597: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054395C200 of size 256
2019-02-13 11:51:34.159812: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054395C300 of size 256
2019-02-13 11:51:34.160009: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054395C400 of size 256
2019-02-13 11:51:34.160188: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054395C500 of size 160581120
2019-02-13 11:51:34.161260: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:665] Chunk at 000000054D280B00 of size 200497920
2019-02-13 11:51:34.161488: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:671]      Summary of in-use Chunks by size: 
2019-02-13 11:51:34.161919: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 54 Chunks of size 256 totalling 13.5KiB
2019-02-13 11:51:34.162069: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 7 Chunks of size 512 totalling 3.5KiB
2019-02-13 11:51:34.162289: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 1 Chunks of size 768 totalling 768B
2019-02-13 11:51:34.162485: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 8 Chunks of size 1280 totalling 10.0KiB
2019-02-13 11:51:34.162658: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 7 Chunks of size 2560 totalling 17.5KiB
2019-02-13 11:51:34.162889: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 7 Chunks of size 36864 totalling 252.0KiB
2019-02-13 11:51:34.163254: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 1 Chunks of size 5120000 totalling 4.88MiB
2019-02-13 11:51:34.164604: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 7 Chunks of size 157351936 totalling 1.03GiB
2019-02-13 11:51:34.164771: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 1 Chunks of size 160581120 totalling 153.14MiB
2019-02-13 11:51:34.164943: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 1 Chunks of size 200497920 totalling 191.21MiB
2019-02-13 11:51:34.165153: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:678] Sum Total of in-use chunks: 1.37GiB
2019-02-13 11:51:34.165372: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:680] Stats: 
Limit:                  1467967078
InUse:                  1467966976
MaxInUse:               1467966976
NumAllocs:                      98
MaxAllocSize:            200497920

2019-02-13 11:51:34.165730: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:279] **************************************************************************************************xx
2019-02-13 11:51:34.166009: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at conv_ops.cc:682 : Resource exhausted: OOM when allocating tensor with shape[32,32,3,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/CNNGestureRecognizer-master/trackgesture.py", line 375, in <module>
    Main()
  File "C:/Users/Administrator/Desktop/CNNGestureRecognizer-master/trackgesture.py", line 209, in Main
    myNN.trainModel(mod)
  File "C:\Users\Administrator\Desktop\CNNGestureRecognizer-master\gestureCNN.py", line 355, in trainModel
    verbose=1, validation_split=0.2)
  File "C:\Users\Administrator\Python\Python36\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Administrator\Python\Python36\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Administrator\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Administrator\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Administrator\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1382, in __call__
    run_metadata_ptr)
  File "C:\Users\Administrator\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,32,3,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: conv2d_2/convolution = Conv2D[T=DT_FLOAT, _class=["loc:@training/Adadelta/gradients/conv2d_2/convolution_grad/Conv2DBackpropFilter"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](activation_1/Relu, conv2d_2/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: dense_2/BiasAdd/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_222_dense_2/BiasAdd", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by asingh33** [comment]
OOM stands for out of memory, my guess would be that your setup might not have enough RAM.
What config are you running on ?

**Comment by asingh33** [comment]
Closing this as there is no further response from the filer.
