### ISSUE TITLE
ConnectionResetError: [WinError 10054] 

### ISSUE THREAD

**Issue by GPROWIRELESS** [asingh33/CNNGestureRecognizer#63]
Do you want to save the trained weights - y/n ?y
Enter file name - liyizhouT1
Error: failed to send plot to http://127.0.0.1:63342
Traceback (most recent call last):
  File "C:\Program Files\PyCharm 2020.2.2\plugins\python\helpers\pycharm_display\datalore\display\display_.py", line 60, in _send_display_message
    urlopen(url, buffer)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Error: failed to send plot to http://127.0.0.1:63342
Traceback (most recent call last):
  File "C:\Program Files\PyCharm 2020.2.2\plugins\python\helpers\pycharm_display\datalore\display\display_.py", line 60, in _send_display_message
    urlopen(url, buffer)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Vladimir Makarov\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by GPROWIRELESS** [comment]
I try to save the trained weights, then I got this problem.
My vision: python 3.6.6 
h5py 2.9.0
win10
tensorflow 1.2.1
keras 2.0.2
